spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: user
    password: pass
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false